STUDENT_FIRST_NAME = 'first_name'
STUDENT_LAST_NAME = 'last_name'
STUDENT_EMAIL = 'email'
STUDENT_COUNTRY = 'country'
STUDENT_COURSE = 'course'
STUDENT_TABLE = 'Student'
STUDENT_ID = 'student_id'
STUDENT_STUDY_LEVEL = 'study_level'
STUDENT_APPLICATION_ID = 'application_id'


DOC_TABLE = 'Doc'
DOC_CONTENT = 'doc_content'
DOC_ID = 'doc_id'
DOC_STUDENT_ID = 'student_id'
DOC_FILE_NAME = 'file_name'
DOC_UNIVERSITY_NAME = 'university_name'
DOC_SUMMARY = 'summary'

UNIVERSITY_TABLE = 'University'
UNIVERSITY_NAME = 'name'
UNIVERSITY_WEBSITE = 'website'

UNIVERSITY_COURSE_TABLE = 'UniversityCourse'
UNIVERSITY_COURSE_NAME = 'course_name'
UNIVERSITY_COURSE_ENTRY_REQ = 'entry_requirements'
UNIVERSITY_COURSE_ENTRY_REQ_JSON = 'requirements_json'
UNIVERSITY_COURSE_UNI_ID = 'university_id'

UNIVERSITY_COUNTRY_TABLE = 'UniversityCountry'
UNIVERSITY_COUNTRY_NAME = 'country_name'
UNIVERSITY_COUNTRY_ENTRY_REQ = 'entry_requirements'
UNIVERSITY_COUNTRY_ENTRY_REQ_JSON = 'requirements_json'
UNIVERSITY_COUNTRY_UNI_ID = 'university_id'
UNIVERSITY_COUNTRY_COUNTRY_NAME = 'country_name'


APPLICATION_TABLE = 'Application'
APPLICATION_STUDENT_ID = 'student_id'
APPLICATION_UNIVERSITY_ID = 'university_id'
APPLICATION_COURSE_ID = 'course_id'
APPLICATION_COUNTRY_ID = 'country_id'
APPLICATION_STATUS = 'status'
APPLICATION_DATE = 'application_date'
APPLICATION_ID = 'application_id'