STUDENT_CERTIFICATE_SUMMARIZATION = \
"""
Below is a text generated by an OCR model from parsing images in pdfs. 
These are images of student cetificates and qualifications while applying to a university for masters or undergrad programs. 
Summarize the qualifications for each of these while clearly calling out any ambiguous info and info that isnt clearly mentioned. Dont make assumptions. here is the text - 
"""

STUDENT_QUALIFICATION_EVALUATION_SYSTEM_PROMPT = \
""" 
You are an expert in evaluating if a student meets the entry requirement of a university for a particular course.
"""

STUDENT_QUALIFICATION_EVALUATION = \
"""
Given the below student qualification information and the requirements of a university for their programs for students of a specific country. 
Evaluate if the student meets all the criteria. 

Output format -
1. Point of failure: Where the student does not meet criteria.
2. Point of ambiguity: Ambiguous points where either data is absent or the criteria is not clear. Need human intervention.
3. Points of communication: Need to get back to the student since data needed is not provided. here the data isnt ambiguous but isnt present at all.

Here is the student qualification information -
{student_doc_content}

Here are the course requirements of the university -
{course_entry_requirements}

Here are the country requirements of the university -
{country_entry_requirements}
"""

COURSE_UNIVERSITY_REQUIREMENT = \
"""
Below is the requirements of a university for a given course. Summarize it in the form of a course -> requirements form 
"""

COUNTRY_UNIVERSITY_REQUIREMENT = \
"""
Below is the requirements of a university for a student of a particular country. Summarize it in the form of a country -> requirements form 
"""